remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: air

title: "Library data blog"
name: "Libraries Hacked"
description: "Articles and tutorials on library data and open data in libraries."
url: "https://blog.librarydata.uk"
repository: "librarieshacked/librarieshacked.github.io"
logo: "/assets/images/logo88x88.png"
breadcrumbs: true

search: true
words_per_minute: 200

twitter:
  username: "librarieshacked"

author:
  name: "Libraries Hacked"
  avatar: "/images/logo.png"
  bio: "Promoting open data and digital prototypes in libraries"
  email: "info@librarieshacked.org"
  uri: "https://www.librarieshacked.org"
  github: "librarieshacked"
  twitter: "librarieshacked"

include:
  - _pages

# Outputting
permalink: /:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/London

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: false
      related: false
      show_date: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

footer_scripts:
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.12.0/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/PapaParse/4.6.3/papaparse.min.js
  - https://use.fontawesome.com/releases/v5.7.1/js/all.js
  - https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js
  - https://cdn.jsdelivr.net/npm/chart.js
  - /assets/js/main.min.js
  - /js/2016-07-18-https-grading.js
  - /js/2019-05-12-mobile-library-data-scotland.js
  - /js/2023-02-19-a-digital-library-community.js
