remote_theme: mmistakes/minimal-mistakes

locale: "en-GB"
title: "#LibraryData Blog"
description: "Articles and tutorials on library data and open data in libraries."
url: "https://blog.librarydata.uk"
title_separator: "-"
name: "Your Name"
description: "An amazing website."
repository: "librarieshacked/librarieshacked.github.io"
search: true

twitter:
  username: "librarieshacked"

author:
  name   : "Libraries Hacked"
  avatar : "/assets/images/logo.png"
  bio    : "Promoting open data and hacks in libraries"
  email  : "info@librarieshacked.org"
  uri    : "https://www.librarieshacked.org"


# Comments
comments:
  provider: "disqus"
  disqus:
    shortname: "librarieshacked"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true