remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air"

locale: "en-GB"
title: "#LibraryData Blog"
title_separator: "-"
description: "Articles and tutorials on library data and open data in libraries."
url: "https://blog.librarydata.uk"
name: "Libraries Hacked"
repository: "librarieshacked/librarieshacked.github.io"
search: true
words_per_minute: 200

twitter:
  username: "librarieshacked"

author:
  name: "Libraries Hacked"
  avatar: "/images/logo.png"
  bio: "Promoting open data and hacks in libraries"
  email: "info@librarieshacked.org"
  uri: "https://www.librarieshacked.org"
  github: "librarieshacked"
  twitter: &twitter "librarieshacked"

# Outputting
permalink: /:title
paginate: 5
paginate_path: /page:num/
timezone: Europe/London # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Comments
comments:
  provider: "disqus"
  disqus:
    shortname: "librarieshacked"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

footer_scripts:
  - https://cdnjs.cloudflare.com/ajax/libs/PapaParse/4.6.3/papaparse.min.js
  - /js/2016-07-18-https-grading.js