remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dirt"

locale: "en-GB"
title: "Library data blog"
title_separator: "|"
name: "Libraries Hacked"
description: "Articles and tutorials on library data and open data in libraries."
url: "https://blog.librarydata.uk"
repository: "librarieshacked/librarieshacked.github.io"
logo: "/images/logo.png"

search: true
words_per_minute: 200

author:
  name: "Libraries Hacked"
  avatar: "/images/logo.png"
  bio: "Promoting open data and hacks in libraries"
  email: "info@librarieshacked.org"
  uri: "https://www.librarieshacked.org"
  github: "librarieshacked"

# Outputting
permalink: /:title
paginate: 5
paginate_path: /page:num/
timezone: Europe/London

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: false
      related: false
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

footer_scripts:
  - https://cdnjs.cloudflare.com/ajax/libs/PapaParse/4.6.3/papaparse.min.js
  - /assets/js/main.min.js
  - https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js
  - /js/2016-07-18-https-grading.js
  - https://use.fontawesome.com/releases/v5.7.1/js/all.js
