remote_theme: mmistakes/minimal-mistakes
title: Libraries Hacked
description: Promoting open data and hacks in libraries

twitter:
  username: librarieshacked
author:
  avatar: "/images/logo.png"
  location: UK
  email: info@librarieshacked.org

defaults:
  # _posts
  - scope:
      path:
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
